config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show, :create, :new, :edit, :update, :destroy]
  resource :session, only: [:new, :create, :destroy]

  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  get '/construction' => 'pages#construction'
  get '/engineering' => 'pages#engineering'
  get '/contact' => 'pages#contact'
  get '/project' => 'pages#project'
  get '/about' => 'pages#about'
  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true


  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  before_action :ensure_current_user #WITH SOME EXCEPTIONS

  def current_user
    user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def ensure_current_user
    unless current_user do
      flash.notice = "you must be logged in to continue"
      redirect_to new_session_path
    end
  end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def construction_services
  end

  def engineering_services
  end

  def contact
  end

  def projects
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_current_user

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash.notice = "Welcome back #{user.username}"
      redirect_to root_path
    else
      flash[:error] = "Login failed, please try again"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_current_user

  def index
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end
  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "Thanks for registering!"
      redirect_to about_path
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @user.username = @user.username.capitalize
  end

  def edit
    @user = User.find_by(id: params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<div class="sidenav" id="mySidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%= link_to "Home", root_path, id: "baritem"%>
  <%= link_to "About", about_path, id: "baritem" %>
  <%= link_to "Construction Services", construction_path , id: "baritem"%>
  <%= link_to "Engineering Services", engineering_path, id: "baritem" %>
  <%= link_to "Contact", contact_path, id: "baritem"%>
  <%= link_to "Projects", project_path, id: "baritem"%>
  <%= link_to "History", history_path, id: "baritem"%>
  <% if current_user %>
  <h2> Signed in as <%= current_user.username.capitalize%> </h2>
  <%= link_to "Sign Out", logout_path, id: "baritem" %>
  <%else%>
  <%= link_to "Register", register_path, id: "baritem"%>
  <%= link_to "Log In", login_path, id: "baritem" %>
  <%end%>
</div>

<div id="main">
    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>
    <h1> About</h1>
	<p>Field Associates, P.C. is a multi-disciplined consulting engineering firm, centrally located in Nassau County.  We specialize in Environmental Engineering, Electrical, Mechanical (HVAC), Plumbing, Construction Management and Design Services. We were established in February 1975.</p>

	<p>We have served as consultants to a wide variety of clients including Dormitory Authority State of New York, NYS & NYC Department of Transportation, NYS Department of Environmental Conservation, NYC Department of Environmental Protection, Port Authority of NY & NJ, NYS Office of General Services, and other Federal, State and Municipal agencies, as well as private industry. Field Associates is a registered MBE/DBE firm with the State and City of New York.</p>

	<p>We offer a competent, well-integrated and experienced engineers, designers and technical support personnel.  Field Associates' team has the professional talent and innovative know-how to service a full range of Engineering Services.  A Licensed Professional Engineer leads each discipline.  They are all familiar with the New York State, New York City and BOCA Building Code Guidelines.</p>
</div>

app/views/pages/construction.html.erb
<div class="sidenav" id="mySidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%= link_to "Home", root_path, id: "baritem"%>
  <%= link_to "About", about_path, id: "baritem" %>
  <%= link_to "Construction Services", construction_path , id: "baritem"%>
  <%= link_to "Engineering Services", engineering_path, id: "baritem" %>
  <%= link_to "Contact", contact_path, id: "baritem"%>
  <%= link_to "Projects", project_path, id: "baritem"%>
  <%= link_to "History", history_path, id: "baritem"%>
  <% if current_user %>
  <h2> Signed in as <%= current_user.username.capitalize%> </h2>
  <%= link_to "Sign Out", logout_path, id: "baritem" %>
  <%else%>
  <%= link_to "Register", register_path, id: "baritem"%>
  <%= link_to "Log In", login_path, id: "baritem" %>
  <%end%>
</div>

<div id="main">
      <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>

  <h1> Construction Services </h1>
  <h2>Construction Management</h2>

  <p> Our highly qualified Staff of Resident Engineers & Inspectors are specially trained to overcome the many and varied problems encountered in Construction Inspection & Management. Over 95% of them have achieved some degree of NICET Certification. Others are trained in the field use of computers and up to date technological devices.</p>

  <h3> Architectural Engineering: </h3>
  <p> We provide expert Architectural Services for the following:</p>
  <ul>
    <li>Americans with Disabilities Act (ADA) Compliance & Designs Buildings </li>
    <li>Rehabilitation of Private & Commercial Dwellings</li>
    <li> Town Planning</li>
    <li> Churches & Houses of Worship</li>
    <li> Educational Facilities</li>
    <li> Recreational Facilities</li>
    <li> Clinics & Medical Offices</li>
    <li> Plans & Building Permits</li>
    <li>Appraisals</li>
    <li>Low Income Family Developments</li>
      <li> Senior Citizen Housing</li>
      <li>Shopping Centers</li>
    </ul>
    <h4>HVAC & PLUMBING:</h4>
    <p> Our Mechanical Engineers are equipped to handle projects ranging from simple single family housing complex projects rehabilitation and sophisticated HVAC Systems for Commercial and Residential buildings:</p>
    <ul>
      <li>Mechanical Systems</li>
      <li>Fire Safety Systems</li>
      <li>HVAC Systems</li>
      <li>Studies & Reports</li>
      <li>Piping</li>
      <li>Plumbing</li>
      <li>Fire Protection</li>
      <li>Sprinkler Systems</li>
      <li>Waste Water</li>
      <li>Drainage</li>
      <li>Water Tanks</li>
      <li>Treatment Plants</li>
      </ul>
</div>

app/views/pages/contact.html.erb
<div class="sidenav" id="mySidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%= link_to "Home", root_path, id: "baritem"%>
  <%= link_to "About", about_path, id: "baritem" %>
  <%= link_to "Construction Services", construction_path , id: "baritem"%>
  <%= link_to "Engineering Services", engineering_path, id: "baritem" %>
  <%= link_to "Contact", contact_path, id: "baritem"%>
  <%= link_to "Projects", project_path, id: "baritem"%>
  <%= link_to "History", history_path, id: "baritem"%>
  <% if current_user %>
  <h2> Signed in as <%= current_user.username.capitalize%> </h2>
  <%= link_to "Sign Out", logout_path, id: "baritem" %>
  <%else%>
  <%= link_to "Register", register_path, id: "baritem"%>
  <%= link_to "Log In", login_path, id: "baritem" %>
  <%end%>
</div>

<div id="main">    
    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>

<h1> Contact </h1>
  <p>Field Associates, P.C. </p>
  <p> Environmental, Construction Management, Electrical & Mechanical Engineers </p>
  <h2> Leo Field, P.E. President </h2>
    <p> Email: Lfield2272@aol.com </p>
    <p> Phone: (516)-378-2794 </p>
    <p> Fax: (516)-378-4965 </p>
    <p> Address: 379 Nassau Road, Roosevelt, N.Y. 11575 </p>
</div>

app/views/pages/engineering.html.erb
<div class="sidenav" id="mySidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%= link_to "Home", root_path, id: "baritem"%>
  <%= link_to "About", about_path, id: "baritem" %>
  <%= link_to "Construction Services", construction_path , id: "baritem"%>
  <%= link_to "Engineering Services", engineering_path, id: "baritem" %>
  <%= link_to "Contact", contact_path, id: "baritem"%>
  <%= link_to "Projects", project_path, id: "baritem"%>
  <%= link_to "History", history_path, id: "baritem"%>
  <% if current_user %>
  <h2> Signed in as <%= current_user.username.capitalize%> </h2>
  <%= link_to "Sign Out", logout_path, id: "baritem" %>
  <%else%>
  <%= link_to "Register", register_path, id: "baritem"%>
  <%= link_to "Log In", login_path, id: "baritem" %>
  <%end%>
</div>

<div id="main">
    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>
  <h1>ENVIROMENTAL ENGINEERING:</h1>
  <p>Field Associates performs Phase I, II, and III Environmental Impact Studies, Environmental Assessment for Industrial, Commercial and Transportation Projects including:</p>
  <ul>
    <li>Investigations</li>
    <li>Air Quality Studies</li>
    <li>Noise Study</li>
    <li>Compliance with Environmental Laws (Regulations & Permits)</li>
    <li>Surface Water Quality Studies</li>
    <li>Freshwater & Tidal Wetlands Investigations</li>
    <li>Ecological Studies</li>
    <li>Cultural Resources Study</li>
    <li>Flood Plain Study</li>
    <li>Energy Analysis</li>
    <li>Visual Resource Assessment (VRA)</li>
    <li>Underground Storage Tank Services</li>
    <li>Hazardous Materials Assessment</li>
    <li>Hazardous Waste Assessment Report</li>
    <li>Asbestos Assessment</li>
    <li>Public Involvement Meetings and Open House Forums</li>
  </ul>
  <h2>HIGHWAY & CIVIL ENGINEERING:</h2>
  <p>Field Associates P.C. has completed Highway & Civil Engineering, Design & Construction Maintenance Projects throughout New York State:</p>
  <ul>
  <li>Bridge Design & Inspection</li>
  <li>Phases I thru VI</li>
  <li>Highway Drainage & Culvert Designs</li>
  <li>Construction Management & Inspection</li>
  <li>Signage & Pavement Markings</li>
  <li>Highway Lighting & Traffic Signals</li>
  <li>Retaining Walls</li>
  <li>Utilities</li>
  <li>Traffic Maintenance</li>
  <li>Sanitary Systems</li>
  <li>Parking Fields & Recreation Areas</li>
  <li>Water Distribution Systems</li>
  <li>Waterfront Structures</li>
  <li>Site Selection & Development</li>
  <li>Mapping</li>
  <li>Sewage Treatment Systems</li>
  <li>Demolition of Structures</li>
  <li>New Building Design & Construction</li>
  </ul>
  <h3>ELECTRICAL ENGINEERING:</h3>
  <p>From studies to full-scope projects, such as Design & Construction Management Services. Our Electrical Department and its Team of experts have completed projects embracing:</p>
  <ul>
  <li>Electrical Power Distribution</li>
  <li>Motor Controls</li>
  <li>Highway & Bridge Lighting</li>
  <li>Water & Sewer Plant Electrical Systems</li>
  <li>Telemarketing Devices</li>
  <li>Pumping Stations</li>
  <li>Alarm & Intrusion Detection Systems</li>
  <li>Emergency Generators</li>
  <li>Rehabilitation of Buildings</li>
  <li>Security Systems</li>
  <li>Fire Detection</li>
  <li>Energy Conservation Analysis</li>
  <li>Site Utilities</li>
  <li>Traffic Signals</li>
  <li>Parking Fields</li>
  <li>Recreational Areas</li>
  <li>Construction Management</li>
  <li>Feasibility Studies</li>
  </ul>
</div>

app/views/pages/history.html.erb
<div class="sidenav" id="mySidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%= link_to "Home", root_path, id: "baritem"%>
  <%= link_to "About", about_path, id: "baritem" %>
  <%= link_to "Construction Services", construction_path , id: "baritem"%>
  <%= link_to "Engineering Services", engineering_path, id: "baritem" %>
  <%= link_to "Contact", contact_path, id: "baritem"%>
  <%= link_to "Projects", project_path, id: "baritem"%>
  <%= link_to "History", history_path, id: "baritem"%>
  <% if current_user %>
  <h2> Signed in as <%= current_user.username.capitalize%> </h2>
  <%= link_to "Sign Out", logout_path, id: "baritem" %>
  <%else%>
  <%= link_to "Register", register_path, id: "baritem"%>
  <%= link_to "Log In", login_path, id: "baritem" %>
  <%end%>
</div>
<div id="main">
    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>

	<h1> Field Associates History </h1>
  		<p> Field Associates was founded by Leo Field in... </p>
 </div>

app/views/pages/project.html.erb
<div class="sidenav" id="mySidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%= link_to "Home", root_path, id: "baritem"%>
  <%= link_to "About", about_path, id: "baritem" %>
  <%= link_to "Construction Services", construction_path , id: "baritem"%>
  <%= link_to "Engineering Services", engineering_path, id: "baritem" %>
  <%= link_to "Contact", contact_path, id: "baritem"%>
  <%= link_to "Projects", project_path, id: "baritem"%>
  <%= link_to "History", history_path, id: "baritem"%>
  <% if current_user %>
  <h2> Signed in as <%= current_user.username.capitalize%> </h2>
  <%= link_to "Sign Out", logout_path, id: "baritem" %>
  <%else%>
  <%= link_to "Register", register_path, id: "baritem"%>
  <%= link_to "Log In", login_path, id: "baritem" %>
  <%end%>
</div>

<div id="main">
    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>
  <h1> Field Associates has completed or contributed to:</h1>
  <ul>
    <li>                                          <h3>Harlem State Office Building:</h3>
      <img src="http://www.ogs.ny.gov/Global/Images/BU/BA/RPM/ACP.jpg" style="width:200px;height:200px;">
      <p>Renovation and Improvements New Fire Command Station & TV Security:  Work includes electrical distribution, replacement of switchgear, underground distribution system, scheduling, planning, constructability review, construction cost estimate, construction documents, procurement services, site conditioning, safety and quality assurance, monitoring progress of work, information management system to tract all pertinent project information, reporting, contract closeout, review of claims and work distribution, construction field work and deliverables.  These include evaluation of construction bids.  Revisions to bid documents as required.  Budgeting; estimating.  Conducted bi-weekly meetings; preparation of reports; weekly inspections during construction phase.</p></li>

      <li><h3>T.O.B. Town Hall – Electrical & Mechanical Upgrade:</h3>
        <img src="http://cdn.newsday.com/polopoly_fs/1.10820913.1441753836!/httpImage/image.JPG_gen/derivatives/display_600/image.JPG" style="width:200px;height:200px;">
        <p>Pre-construction, construction and post-construction phase services, safety and quality assurance, electrical distribution, scheduling, planning, constructability review, construction cost estimate, construction documents, procurement services, site conditioning, contract closeout, review of claims and work distribution, construction field work and deliverables.</p>
        <h5>Owner: Town of Oyster Bay.</h5>
      </li>

      <li>
        <h3>JFK International Airport, International Arrival Building - Electrical & Mechanical Improvements:</h3>
        <img src="http://www.som.com/FILE/15269/jfkterminal4_788x900_frederickcharles_03jpg.jpg?h=800&s=17" style="width:200px;height:200px;">

        <p>Construction Management services, electrical distribution, scheduling, planning, constructability review, construction cost estimate, construction documents, procurement services, pre-construction, construction and post-construction phase services, safety and quality assurance, monitoring progress of work, information management system to tract all pertinent project information, reporting, site conditioning, contract closeout, review of claims and work distribution, construction field work and deliverables.</p>
        <h5>Owner: PA of NY & NJ, Aviation Division.</h5>
      </li>

      <li>
        <h3>St. Mary’s Outpatient Health Center,
          Brooklyn, New York – Emergency Generator    & Heating System:</h3>
          <img src="http://www.brooklyneagle.com/sites/default/files/styles/panopoly_image_original/public/st.-marys-hospital-back.jpg?itok=huDCWlQR" style="width:200px;height:200px;">
          <p>Work include electrical distribution, generator upgrades, replace the medium voltage switchgear, replace the medium voltage underground distribution system, replace panels and feeders, automatic transfer switch and emergency distribution panel, scheduling, planning, constructability review, construction cost estimate, construction documents. Evaluation of construction bids.  Revisions to bid documents as required.  Budgeting; estimating.  Conducted bi-weekly meetings; preparation of reports; weekly inspections during construction phase.  Site conditioning, safety and quality assurance, monitoring progress of work.</p>

          <h5>Owner: Dormitory Authority, State of NY</h5>
        </li>

        <li>
          <h3>Manhattan Psychiatric Center – Emergency Generator System:</h3>
          <img src="https://www.omh.ny.gov/omhweb/facilities/mapc/images/manhattan.jpg" style="width:200px;height:200px;">
          <p>Work consist of pre-construction, construction and post-construction phase services,  electrical distribution, generator upgrades, replace the medium voltage switchgear, replace the medium voltage underground distribution system, replace panels and feeders, automatic transfer switch and emergency distribution panel.  Constructability review, construction cost estimate, construction documents, procurement services, site conditioning, safety and quality assurance, monitoring progress of work, reporting, contract closeout, review of claims and work distribution, construction field work and deliverables.  Revisions to bid documents as required.  Budgeting; estimating.  Meetings and  preparation of reports.</p>

          <h5>Owner: Dormitory Authority State of NY.</h5>
        </li>


        <li>
          <h3>Planting Fields Arboretum, South Oyster Bay, NY - Rehabilitation of Emergency Generator & Heating System:</h3>
          <img src="http://1.bp.blogspot.com/-kaXpD2xBLk0/Tc1qGARF0wI/AAAAAAAAAOo/SkvMrTzltZM/s1600/PFA%2B1.JPG" style="width:200px;height:200px;">
          <p>Replace the medium voltage switchgear, replace the medium voltage underground distribution system, replace panels and feeders, automatic transfer switch and emergency distribution panel,
            electrical distribution, generator upgrades, scheduling, planning, constructability review, construction site conditioning, safety and quality assurance, monitoring progress of work, information management system to tract all pertinent project information, reporting, contract closeout. Meetings; preparation of reports; weekly inspections during construction phase.  Review of claims and work distribution, construction field work and deliverables.</p>
            <h5>Owner: NYS, Office of Parks & Historic    Preservation, NY.</h5>
          </li>

          <li>
           <h3>Bellevue Hospital Center.
            Emergency Generator, For Life Safety System. </h3>
            <img src="http://www.nychealthandhospitals.org/hhc/images/pressroom/20150707-press-release-HHC-Bellevue-named-national-Ebola-leader.jpg" style="width:200px;height:200px;">
            <p>Work include generator upgrades, electrical distribution, replace the medium voltage switchgear, replace the medium voltage underground distribution system, replace panels and feeders, automatic transfer switch and emergency distribution panel.  Scheduling, planning, constructability review, construction cost estimate, construction documents, site conditioning, safety and quality assurance, weekly inspections during construction phase.  Reporting, contract closeout, review of claims and work distribution, construction field work and deliverables.  These include evaluation of construction bids.  Revisions to bid documents as required.  Budgeting; estimating.  Bi-weekly meetings; preparation of reports.</p>

            <h5>Owner: New York City, Health & Hospital Corp.</h5>
          </li>

          <li>
            <h3>Parkside Correctional Facilities Bronx, New York - Mechanical and Electrical Rehabilitation:</h3>
            <img src="https://cdn1.vox-cdn.com/thumbor/quqwdyCJPT5-8IpLeR4cCNrVrNE=/109x0:390x375/680x907/filters:format(webp)/cdn0.vox-cdn.com/uploads/chorus_image/image/47900181/caledonian.0.jpg" style="width:200px;height:200px;">
            <p>Project provided design services for the upgrade of electrical distribution panels and fixtures throughout the facility.  Work included inspections and cost estimating.   Installation of vandal-proof lighting.  Connections to UPS systems.  HVAC ventilation ductwork.  Security backup lighting.  Installation of fans and registers.</p>

            <h5>Owner: New York State, Office of General Services.</h5>
          </li>
        </ul>
</div>

app/views/users/index.html.erb
<div class="sidenav" id="mySidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
	<%= link_to "Home", root_path, id: "baritem"%>
	<%= link_to "About", about_path, id: "baritem" %>
	<%= link_to "Construction Services", construction_path , id: "baritem"%>
	<%= link_to "Engineering Services", engineering_path, id: "baritem" %>
	<%= link_to "Contact", contact_path, id: "baritem"%>
	<%= link_to "Projects", project_path, id: "baritem"%>
	<%= link_to "History", history_path, id: "baritem"%>
	<% if current_user %>
	<h2> Signed in as <%= current_user.username.capitalize%> </h2>
	<%= link_to "Sign Out", logout_path, id: "baritem" %>
	<%else%>
	<%= link_to "Register", register_path, id: "baritem"%>
	<%= link_to "Log In", login_path, id: "baritem" %>
	<%end%>
</div>
<div id="main">
	 <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>
		<h2>FIELD ASSOCIATES, P.C. - CONSULTING ENGINEERS</h2>
		<h1> Engineers of the Future </h1>
			 <div id="cf7" class="shadow">
	  <img class='opaque' src="http://www.ogs.ny.gov/Global/Images/BU/BA/RPM/ACP.jpg" style="width:300px;height:300px;" />
	  <img src="http://www.brooklyneagle.com/sites/default/files/styles/panopoly_image_original/public/st.-marys-hospital-back.jpg?itok=huDCWlQR" style="width:300px;height:300px;" />
	  <img src="https://cdn1.vox-cdn.com/thumbor/quqwdyCJPT5-8IpLeR4cCNrVrNE=/109x0:390x375/680x907/filters:format(webp)/cdn0.vox-cdn.com/uploads/chorus_image/image/47900181/caledonian.0.jpg" style="width:300px;height:300px;"
	/>
	  <img src="http://www.nychealthandhospitals.org/hhc/images/pressroom/20150707-press-release-HHC-Bellevue-named-national-Ebola-leader.jpg" style="width:300px;height:300px;">/>
	</div>
	<p id="cf7_controls">
	  <span class="selected">Harlem State Office Building</span>
	  <span>St. Mary’s Outpatient Health Center</span>
	  <span>Parkside Correctional Facility</span>
	  <span>JFK International Airport, Arrival Building </span>
	</p>
 </div>

app/views/users/new.html.erb
<%=form_for @user do |f| %>

  <fieldset>
    <legend>Create an Account </legend>
    <div>
      <%= f.label :username %>
      <%= f.text_field :username%>
    </div>
    <div>
      <%=f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation%>
    </div>

    <div>
      <%=f.submit 'Submit'%>
    </div>
  </fieldset>
<%end%>